/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e2e2e5",
        "on-secondary-fixed-variant": "#454749",
        "on-error-container": "#93000a",
        "surface-container": "#e5eeff",
        "on-secondary": "#ffffff",
        "primary-container": "#ff5f40",
        "error": "#ba1a1a",
        "on-primary-container": "#5f0a00",
        "surface-container-low": "#eff4ff",
        "primary-fixed": "#ffdad3",
        "secondary-container": "#e2e2e5",
        "tertiary-container": "#768cff",
        "tertiary": "#2e4edc",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#ffb4a5",
        "on-primary-fixed-variant": "#8e1500",
        "on-tertiary-fixed": "#001159",
        "on-primary-fixed": "#3e0400",
        "outline-variant": "#e3beb7",
        "surface-bright": "#f8f9ff",
        "on-error": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "surface-tint": "#b3290f",
        "on-secondary-fixed": "#1a1c1e",
        "tertiary-fixed": "#dee1ff",
        "surface-variant": "#d3e4fe",
        "outline": "#8e706a",
        "background": "#f8f9ff",
        "primary": "#b3290f",
        "on-background": "#0b1c30",
        "on-primary": "#ffffff",
        "inverse-primary": "#ffb4a5",
        "on-surface": "#0b1c30",
        "on-tertiary-container": "#001f85",
        "on-surface-variant": "#5a413b",
        "secondary": "#5d5e61",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#213145",
        "on-tertiary-fixed-variant": "#0031c4",
        "secondary-fixed-dim": "#c6c6c9",
        "tertiary-fixed-dim": "#bac3ff",
        "surface-dim": "#cbdbf5",
        "surface": "#f8f9ff",
        "on-secondary-container": "#636467",
        "inverse-on-surface": "#eaf1ff",
        "error-container": "#ffdad6",
        "surface-container-high": "#dce9ff"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "container-padding": "16px",
        "xl": "32px",
        "gutter": "12px",
        "base": "4px",
        "lg": "24px"
      },
      fontFamily: {
        "headline-sm": ["Hanken Grotesk"],
        "label-md": ["JetBrains Mono"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "title-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"]
      },
    },
  },
  plugins: [],
};
